/* FACULDADE PITÁGORAS - UNIDADE BETIM
   CURSO: Ciência da Computação
   DISCIPLINA: Programação em Banco de Dados
   PROJETO: Votação On-Line®
   AUTOR: Discentes + Docente
   DATA INICIO: 21/08/2.019
   VERSÃO: 1 - 210819
   VERSÃO: 2 - 280819
   VERSÃO: 3 - 040919
*/

-- 00. Validação do Script
DROP DATABASE IF EXISTS FAPBETIM 

-- 01. Create Database
CREATE DATABASE FAPBETIM;

-- 02. Set Database
USE FAPBETIM;

-- 03. Table Eleitor
CREATE TABLE ELEITOR
( IDEL INT IDENTITY(1,1),
  NOME VARCHAR(80) NOT NULL,
  CPF CHAR(11) UNIQUE,
  DTNASC DATE NOT NULL,
  SENHA VARCHAR(08) NOT NULL,
  EMAIL VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY(IDEL));

 -- 04. Select Eleitor
 SELECT * FROM ELEITOR;

 -- 05. Insert Eleitor
 INSERT INTO ELEITOR (NOME,CPF,DTNASC,SENHA,EMAIL)
      VALUES ('CRISTIANO MARTINS NUNES','12345678900',
	          '1968-12-31','31121968','cristiano.nunes@kroton.com.br');

-- 06. Table TipoEleitor
CREATE TABLE TIPOELEITOR
( IDTE INT IDENTITY(1,1),
  DESCRICAO VARCHAR(20) NOT NULL,
  PRIMARY KEY(IDTE));

-- 06.1 Relacionamento TipoEleitor x Eleitor
ALTER TABLE ELEITOR
ADD IDTE INT

ALTER TABLE ELEITOR
ADD FOREIGN KEY (IDTE) REFERENCES TIPOELEITOR (IDTE)

-- 07. Insert TipoEleitor
INSERT INTO TIPOELEITOR (DESCRICAO)
	 VALUES ('ADMINISTRATIVO'),('ALUNO'),('PROFESSOR'),('VISITANTE');

-- 08. Select TipoEleitor
SELECT * FROM TIPOELEITOR;

-- 09. Table Curso
CREATE TABLE CURSO
( IDCU INT IDENTITY(1,1),
  NOMECURSO VARCHAR(45) NOT NULL,
  PRIMARY KEY(IDCU));

-- 10. Select Curso
SELECT * FROM CURSO;

-- 11. Insert Curso
INSERT INTO CURSO (NOMECURSO)
     VALUES ('CIÊNCIA DA COMPUTAÇÃO'),('ENGENHARIA MECÂNICA'),
	        ('ENGENHARIA CIVIL');

-- 12. Table Projeto
CREATE TABLE PROJETO
( IDPR INT IDENTITY(1,1),
  NOMEPROJETO TEXT NOT NULL,
  PRIMARY KEY(IDPR));

-- 12.1 Relacionamento Projeto x Curso
ALTER TABLE PROJETO
ADD IDCU INT

ALTER TABLE PROJETO
ADD FOREIGN KEY (IDCU) REFERENCES CURSO (IDCU)

-- 13. Table Votacao
CREATE TABLE VOTACAO
( IDVO INT IDENTITY(1,1),
  CPF CHAR(11) NOT NULL,
  IDPR INT,
  DATAHORA DATETIME DEFAULT GETDATE( ),
  PRIMARY KEY (IDVO))

-- 13.1 Relacionamento Votacao x Eleitor
ALTER TABLE VOTACAO
ADD FOREIGN KEY (CPF) REFERENCES ELEITOR (CPF)

-- 13.2 Relacionamento Votacao x Projeto x Curso
ALTER TABLE VOTACAO
ADD FOREIGN KEY (IDPR) REFERENCES PROJETO (IDPR)
